package cn.kdcrm.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class TrainInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.TRAIN_ID
     *
     * @mbggenerated
     */
    private BigDecimal trainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.TRAIN_NO
     *
     * @mbggenerated
     */
    private String trainNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.START_STATION
     *
     * @mbggenerated
     */
    private String startStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.ARRIVAL_STATION
     *
     * @mbggenerated
     */
    private String arrivalStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.ARRIVAL_TIME
     *
     * @mbggenerated
     */
    private String arrivalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.RUNTIME
     *
     * @mbggenerated
     */
    private String runtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAIN_INFO.MILE
     *
     * @mbggenerated
     */
    private BigDecimal mile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRAIN_INFO
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.TRAIN_ID
     *
     * @return the value of TRAIN_INFO.TRAIN_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.TRAIN_ID
     *
     * @param trainId the value for TRAIN_INFO.TRAIN_ID
     *
     * @mbggenerated
     */
    public void setTrainId(BigDecimal trainId) {
        this.trainId = trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.TRAIN_NO
     *
     * @return the value of TRAIN_INFO.TRAIN_NO
     *
     * @mbggenerated
     */
    public String getTrainNo() {
        return trainNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.TRAIN_NO
     *
     * @param trainNo the value for TRAIN_INFO.TRAIN_NO
     *
     * @mbggenerated
     */
    public void setTrainNo(String trainNo) {
        this.trainNo = trainNo == null ? null : trainNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.START_STATION
     *
     * @return the value of TRAIN_INFO.START_STATION
     *
     * @mbggenerated
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.START_STATION
     *
     * @param startStation the value for TRAIN_INFO.START_STATION
     *
     * @mbggenerated
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation == null ? null : startStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.ARRIVAL_STATION
     *
     * @return the value of TRAIN_INFO.ARRIVAL_STATION
     *
     * @mbggenerated
     */
    public String getArrivalStation() {
        return arrivalStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.ARRIVAL_STATION
     *
     * @param arrivalStation the value for TRAIN_INFO.ARRIVAL_STATION
     *
     * @mbggenerated
     */
    public void setArrivalStation(String arrivalStation) {
        this.arrivalStation = arrivalStation == null ? null : arrivalStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.START_TIME
     *
     * @return the value of TRAIN_INFO.START_TIME
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.START_TIME
     *
     * @param startTime the value for TRAIN_INFO.START_TIME
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.ARRIVAL_TIME
     *
     * @return the value of TRAIN_INFO.ARRIVAL_TIME
     *
     * @mbggenerated
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.ARRIVAL_TIME
     *
     * @param arrivalTime the value for TRAIN_INFO.ARRIVAL_TIME
     *
     * @mbggenerated
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime == null ? null : arrivalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.TYPE
     *
     * @return the value of TRAIN_INFO.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.TYPE
     *
     * @param type the value for TRAIN_INFO.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.RUNTIME
     *
     * @return the value of TRAIN_INFO.RUNTIME
     *
     * @mbggenerated
     */
    public String getRuntime() {
        return runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.RUNTIME
     *
     * @param runtime the value for TRAIN_INFO.RUNTIME
     *
     * @mbggenerated
     */
    public void setRuntime(String runtime) {
        this.runtime = runtime == null ? null : runtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAIN_INFO.MILE
     *
     * @return the value of TRAIN_INFO.MILE
     *
     * @mbggenerated
     */
    public BigDecimal getMile() {
        return mile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAIN_INFO.MILE
     *
     * @param mile the value for TRAIN_INFO.MILE
     *
     * @mbggenerated
     */
    public void setMile(BigDecimal mile) {
        this.mile = mile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAIN_INFO
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trainId=").append(trainId);
        sb.append(", trainNo=").append(trainNo);
        sb.append(", startStation=").append(startStation);
        sb.append(", arrivalStation=").append(arrivalStation);
        sb.append(", startTime=").append(startTime);
        sb.append(", arrivalTime=").append(arrivalTime);
        sb.append(", type=").append(type);
        sb.append(", runtime=").append(runtime);
        sb.append(", mile=").append(mile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}