package cn.kdcrm.service;

import cn.kdcrm.pojo.SystemUserinfo;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;

import java.util.List;

public interface SystemUserinfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userinfoUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int insert(SystemUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    SystemUserinfo selectByPrimaryKey(String userinfoUid);

    /**
     *
     * @param pageNum 当前页
     * @param pageSize 每页显示的条数
     * @return
     */
    PageInfo<SystemUserinfo> selectAll(SystemUserinfo systemUserinfo,int pageNum, int pageSize);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemUserinfo record);

    /**
     * 登录
     * @param userinfoLoginid
     * @param userinfoPassword
     * @return
     */
    SystemUserinfo login( String userinfoLoginid,  String userinfoPassword);

}
