package cn.kdcrm.mapper;

import cn.kdcrm.pojo.SystemUserinfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SystemUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userinfoUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int insert(SystemUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    SystemUserinfo selectByPrimaryKey(String userinfoUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    List<SystemUserinfo> selectAll(SystemUserinfo systemUserinfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemUserinfo record);

    SystemUserinfo login(@Param("userinfoLoginid") String userinfoLoginid, @Param("userinfoPassword")  String userinfoPassword);

}